apiVersion: v2
name: k8s-namespace-sync
description: A Helm chart for K8s Namespace Sync Controller
type: application
version: 0.4.0
appVersion: "v0.4.0"

kubeVersion: ">=1.25.0-0"

keywords:
  - kubernetes
  - namespace
  - sync
  - configmap
  - secret

home: https://github.com/somaz94/k8s-namespace-sync
sources:
  - https://github.com/somaz94/k8s-namespace-sync

maintainers:
  - name: somaz94
    url: https://github.com/somaz94

icon: https://raw.githubusercontent.com/somaz94/k8s-namespace-sync/main/docs/images/logo.png