apiVersion: v2
name: k8s-namespace-sync
description: A Helm chart for K8s Namespace Sync Controller
type: application
version: 0.1.0
appVersion: "v0.1.4"

# Dependencies and requirements
kubeVersion: ">=1.16.0-0"

# Keywords and categories for documentation
keywords:
  - kubernetes
  - namespace
  - sync
  - configmap
  - secret

# Home page, sources, and documentation
home: https://github.com/somaz94/k8s-namespace-sync
sources:
  - https://github.com/somaz94/k8s-namespace-sync

# Maintainer information
maintainers:
  - name: somaz94
    url: https://github.com/somaz94

# Annotations for CRD handling
annotations:
  # This indicates that CRDs are required and should be created first
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "-5"

# Icon for the chart (optional)
icon: https://raw.githubusercontent.com/somaz94/k8s-namespace-sync/main/docs/images/logo.png