{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-namespace-sync.fullname" . }}-manager-rolebinding
  labels:
    {{- include "k8s-namespace-sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-namespace-sync.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-namespace-sync.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-namespace-sync.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "k8s-namespace-sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-namespace-sync.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-namespace-sync.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}
