{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "k8s-namespace-sync.labels" . | nindent 4 }}
    control-plane: controller-manager
    kubernetes.io/metadata.name: {{ .Values.namespace }}
{{- end }}
