{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-namespace-sync.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-namespace-sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-namespace-sync.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-namespace-sync.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}
