apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-namespace-sync.fullname" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-namespace-sync.labels" . | nindent 4 }}
    control-plane: controller-manager
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.service.port }}
      protocol: TCP
  selector:
    {{- include "k8s-namespace-sync.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager