# permissions for end users to view namespacesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-namespace-sync
    app.kubernetes.io/managed-by: kustomize
  name: namespacesync-viewer-role
rules:
- apiGroups:
  - sync.nsync.dev
  resources:
  - namespacesyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.nsync.dev
  resources:
  - namespacesyncs/status
  verbs:
  - get
