---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sync.nsync.dev
  resources:
  - namespacesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.nsync.dev
  resources:
  - namespacesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - sync.nsync.dev
  resources:
  - namespacesyncs/status
  verbs:
  - get
  - patch
  - update
