apiVersion: v1
kind: Secret
metadata:
  name: test-secret2
  namespace: default
type: Opaque
stringData:
  username: admin2
  password: test1234
  api-key: abcd1234-test-key
  config.json: |
    {
      "database": {
        "host": "db.example.com",
        "port": "5432"
      }
    }
