name: E2E Tests

on:
  push:
    paths:
      - '**.go'                           # Go 소스 파일
      - 'go.mod'                          # Go 모듈 파일
      - 'go.sum'                          # Go 모듈 해시
      - 'Makefile'                        # Makefile
      - '.github/workflows/test-e2e.yml'  # 워크플로우 파일 자체
      - 'config/**'                       # Kubernetes 설정 파일
      - 'test/e2e/**'                     # E2E 테스트 파일
      - 'internal/**'                     # 내부 파일
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/test-e2e.yml'
      - 'config/**'
      - 'test/e2e/**'
      - 'internal/**'                     

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Install required tools
        env:
          GOOS: linux
          GOARCH: amd64
        run: make install-tools

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
